# Generated by Django 5.0.6 on 2025-11-26 23:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(db_index=True, max_length=18, unique=True, verbose_name='CNPJ')),
                ('ie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('distancia', models.DecimalField(blank=True, decimal_places=2, help_text='Distância em KM da base até o cliente', max_digits=10, null=True, verbose_name='Distância da Base (KM)')),
                ('tipo_frete', models.CharField(choices=[('CIF', 'CIF'), ('FOB', 'FOB')], default='CIF', help_text='Tipo de frete padrão para este cliente', max_length=3, verbose_name='Tipo de Frete Padrão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='CompartimentacaoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boca', models.PositiveSmallIntegerField(help_text='Número da boca (1-9)', verbose_name='Número da Boca')),
                ('capacidade_m3', models.DecimalField(decimal_places=2, help_text='Capacidade da boca em metros cúbicos', max_digits=10, verbose_name='Capacidade (M³)')),
            ],
            options={
                'verbose_name': 'Compartimento de Veículo',
                'verbose_name_plural': 'Compartimentos de Veículos',
                'db_table': 'compartimentacao_veiculo',
                'ordering': ['veiculo', 'numero_boca'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(db_index=True, max_length=14, unique=True, verbose_name='CPF')),
                ('cnh', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='CNH')),
                ('categoria_cnh', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('AB', 'AB'), ('AC', 'AC'), ('AD', 'AD'), ('AE', 'AE')], max_length=5, null=True, verbose_name='Categoria CNH')),
                ('validade_cnh', models.DateField(blank=True, null=True, verbose_name='Validade CNH')),
                ('nr20_validade', models.DateField(blank=True, help_text='Norma Regulamentadora 20 - Inflamáveis e Combustíveis', null=True, verbose_name='NR20 - Validade')),
                ('nr35_validade', models.DateField(blank=True, help_text='Norma Regulamentadora 35 - Trabalho em Altura', null=True, verbose_name='NR35 - Validade')),
                ('mopp_validade', models.DateField(blank=True, help_text='Movimentação Operacional de Produtos Perigosos', null=True, verbose_name='MOPP - Validade')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'db_table': 'motorista',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='veiculo',
            name='afericao_validade',
            field=models.DateField(blank=True, help_text='Aferição de Tacógrafo', null=True, verbose_name='Aferição - Validade'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cipp_validade',
            field=models.DateField(blank=True, help_text='Certificado de Inspeção para Transporte de Produtos Perigosos', null=True, verbose_name='CIPP - Validade'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='civ_validade',
            field=models.DateField(blank=True, help_text='Certificado de Inspeção Veicular', null=True, verbose_name='CIV - Validade'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='crlv_validade',
            field=models.DateField(blank=True, help_text='Certificado de Registro e Licenciamento de Veículo', null=True, verbose_name='CRLV - Validade'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cronotacografo_validade',
            field=models.DateField(blank=True, help_text='Validade da aferição do cronotacógrafo', null=True, verbose_name='Cronotacógrafo - Validade'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_carroceria',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Carroceria'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_rodado',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Rodado'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='capacidade_m3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidade total do veículo em metros cúbicos', max_digits=10, null=True, verbose_name='Capacidade Total (M³)'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['placa'], name='veiculo_placa_76c41d_idx'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['ativo', 'placa'], name='veiculo_ativo_df6752_idx'),
        ),
        migrations.AlterModelTable(
            name='veiculo',
            table='veiculo',
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cnpj'], name='cliente_cnpj_87b524_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ativo', 'razao_social'], name='cliente_ativo_8d0a27_idx'),
        ),
        migrations.AddField(
            model_name='compartimentacaoveiculo',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartimentos', to='transport.veiculo', verbose_name='Veículo'),
        ),
        migrations.AddIndex(
            model_name='motorista',
            index=models.Index(fields=['cpf'], name='motorista_cpf_da6713_idx'),
        ),
        migrations.AddIndex(
            model_name='motorista',
            index=models.Index(fields=['cnh'], name='motorista_cnh_35986c_idx'),
        ),
        migrations.AddIndex(
            model_name='motorista',
            index=models.Index(fields=['ativo', 'nome'], name='motorista_ativo_9e1214_idx'),
        ),
        migrations.AddIndex(
            model_name='compartimentacaoveiculo',
            index=models.Index(fields=['veiculo', 'numero_boca'], name='compartimen_veiculo_100d31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compartimentacaoveiculo',
            unique_together={('veiculo', 'numero_boca')},
        ),
    ]
