# Generated by Django 5.0.6 on 2025-12-04 00:32

import django.db.models.deletion
import transport.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_adicionar_cliente_motorista_compartimentacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAnexo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('proposta', 'Proposta Comercial'), ('procuracao', 'Procuração'), ('cnh', 'CNH'), ('rg', 'RG'), ('cpf', 'CPF'), ('comprovante_residencia', 'Comprovante de Residência'), ('certificado_nr20', 'Certificado NR20'), ('certificado_nr35', 'Certificado NR35'), ('certificado_mopp', 'Certificado MOPP'), ('aso', 'ASO - Atestado de Saúde Ocupacional'), ('ficha_registro', 'Ficha de Registro'), ('crlv', 'CRLV'), ('civ', 'CIV - Certificado de Inspeção Veicular'), ('cipp', 'CIPP - Transporte Produtos Perigosos'), ('seguro', 'Apólice de Seguro'), ('certificado_tacografo', 'Certificado Tacógrafo'), ('laudo_vistoria', 'Laudo de Vistoria'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Tipo de Documento')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome/Descrição')),
                ('arquivo', models.FileField(help_text='Formatos aceitos: PDF, JPG, PNG, DOC, DOCX (max 10MB)', upload_to=transport.models.documento_anexo_path, verbose_name='Arquivo')),
                ('tamanho', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('tipo_mime', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo MIME')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexos', to='transport.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_criados', to=settings.AUTH_USER_MODEL)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexos', to='transport.motorista')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexos', to='transport.veiculo')),
            ],
            options={
                'verbose_name': 'Documento Anexo',
                'verbose_name_plural': 'Documentos Anexos',
                'db_table': 'documento_anexo',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['cliente', 'tipo'], name='documento_a_cliente_d6fb3c_idx'), models.Index(fields=['motorista', 'tipo'], name='documento_a_motoris_77c860_idx'), models.Index(fields=['veiculo', 'tipo'], name='documento_a_veiculo_9a0f86_idx'), models.Index(fields=['validade'], name='documento_a_validad_563d0f_idx')],
            },
        ),
    ]
