# Generated by Django 5.0.6 on 2025-12-04 02:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_adicionar_documento_anexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manutencaoveiculo',
            options={'ordering': ['-data_agendada', '-criado_em'], 'verbose_name': 'Manutenção de Veículo', 'verbose_name_plural': 'Manutenções de Veículos'},
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Custo Total'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='data_agendada',
            field=models.DateField(blank=True, null=True, verbose_name='Data Agendada'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='data_realizada',
            field=models.DateField(blank=True, null=True, verbose_name='Data Realizada'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Serviço'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Fornecedor/Oficina'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('preditiva', 'Preditiva')], default='preventiva', max_length=20, null=True, verbose_name='Tipo de Manutenção'),
        ),
        migrations.AlterField(
            model_name='manutencaoveiculo',
            name='data_servico',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Serviço'),
        ),
        migrations.AlterField(
            model_name='manutencaoveiculo',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=44, null=True, verbose_name='Número Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='manutencaoveiculo',
            name='quilometragem',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quilometragem Atual'),
        ),
        migrations.AlterField(
            model_name='manutencaoveiculo',
            name='servico_realizado',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='manutencaoveiculo',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=20),
        ),
        migrations.AlterField(
            model_name='manutencaoveiculo',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
    ]
