# Generated by Django 5.0.6 on 2025-12-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_add_campo_pago_cte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctecancelamento',
            name='id_evento',
            field=models.CharField(max_length=60, unique=True, verbose_name='ID Evento'),
        ),
        migrations.AlterField(
            model_name='mdfecancelamento',
            name='id_evento',
            field=models.CharField(max_length=60, unique=True, verbose_name='ID Evento'),
        ),
        migrations.AlterField(
            model_name='mdfecancelamentoencerramento',
            name='id_evento',
            field=models.CharField(max_length=60, unique=True, verbose_name='ID Evento'),
        ),
    ]
