# Generated by Django 5.0.6 on 2025-12-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_aumentar_id_evento_para_60_chars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctecancelamento',
            name='id_retorno',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID Retorno'),
        ),
        migrations.AlterField(
            model_name='ctecancelamento',
            name='n_prot_retorno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Protocolo Evento'),
        ),
        migrations.AlterField(
            model_name='mdfecancelamento',
            name='id_retorno',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID Retorno'),
        ),
        migrations.AlterField(
            model_name='mdfecancelamento',
            name='n_prot_retorno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Protocolo Evento'),
        ),
        migrations.AlterField(
            model_name='mdfecancelamentoencerramento',
            name='id_retorno',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID Retorno'),
        ),
        migrations.AlterField(
            model_name='mdfecancelamentoencerramento',
            name='n_prot_cancelar',
            field=models.CharField(max_length=20, verbose_name='Protocolo Encerramento a Cancelar'),
        ),
        migrations.AlterField(
            model_name='mdfecancelamentoencerramento',
            name='n_prot_retorno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Protocolo Evento'),
        ),
    ]
