# Generated by Django 5.0.6 on 2025-12-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_atualizar_manutencao_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctedocumento',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='ctedocumento',
            name='observacao_pagamento',
            field=models.TextField(blank=True, null=True, verbose_name='Observação do Pagamento'),
        ),
        migrations.AddField(
            model_name='ctedocumento',
            name='pago',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Pago'),
        ),
    ]
