# Generated by Django 5.0.6 on 2025-12-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_aumentar_campos_id_retorno_e_prot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctecancelamento',
            name='arquivo_xml_evento',
            field=models.TextField(verbose_name='XML Evento Cancelamento', null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='mdfecancelamento',
            name='arquivo_xml_evento',
            field=models.TextField(verbose_name='XML Evento Cancelamento', null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='mdfecancelamentoencerramento',
            name='arquivo_xml_evento',
            field=models.TextField(verbose_name='XML Evento Canc. Encerramento', null=True, blank=True),
        ),
    ]
