# Generated by Django 5.2.9 on 2026-06-13 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0018_add_arquivo_nota_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoanexo',
            name='cte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexos', to='transport.ctedocumento'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='toma',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Remetente'), (1, 'Expedidor'), (2, 'Recebedor'), (3, 'Destinatário'), (4, 'Outros')], help_text='0=Remetente, 1=Expedidor, 2=Recebedor, 3=Destinatário, 4=Outros', null=True, verbose_name='Tomador Serviço'),
        ),
        migrations.AlterField(
            model_name='pagamentoproprio',
            name='motorista_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Condutor'),
        ),
        migrations.AlterField(
            model_name='pagamentoproprio',
            name='motorista_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Condutor'),
        ),
    ]
