# Generated by Django 5.2.9 on 2026-06-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0019_add_cte_to_documento_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctecarga',
            name='produto_predominante',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Produto Predominante'),
        ),
        migrations.AlterField(
            model_name='ctecarga',
            name='valor_carga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Total Mercadorias'),
        ),
        migrations.AlterField(
            model_name='ctedestinatario',
            name='razao_social',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Razão Social/Nome'),
        ),
        migrations.AlterField(
            model_name='cteemitente',
            name='crt',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='CRT'),
        ),
        migrations.AlterField(
            model_name='cteemitente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Razão Social/Nome'),
        ),
        migrations.AlterField(
            model_name='cteexpedidor',
            name='razao_social',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Razão Social/Nome'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='ambiente',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ambiente (1=Prod, 2=Hom)'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='cfop',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CFOP'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='codigo_control',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Código Numérico Chave'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='codigo_mun_envio',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Código Município Envio'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='codigo_mun_fim',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Código Município Fim Prest.'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='codigo_mun_ini',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Código Município Início Prest.'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='codigo_uf',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Código UF Emitente'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='data_emissao',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data/Hora Emissão'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='digito_verificador',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dígito Verificador Chave'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='modal',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Modal'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='modelo',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='natureza_operacao',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Natureza da Operação'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='nome_mun_envio',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome Município Envio'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='nome_mun_fim',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome Município Fim Prest.'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='nome_mun_ini',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome Município Início Prest.'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número CT-e'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='processo_emissao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Processo Emissão'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='serie',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='tipo_cte',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tipo CT-e (0=Normal, 1=Compl, 2=Anul, 3=Subst)'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='tipo_emissao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tipo Emissão'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='tipo_impressao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tipo Impressão DACTE'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='tipo_servico',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo Serviço'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='uf_envio',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Envio'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='uf_fim',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Fim Prest.'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='uf_ini',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Início Prest.'),
        ),
        migrations.AlterField(
            model_name='cteidentificacao',
            name='versao_processo',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Versão Processo Emissão'),
        ),
        migrations.AlterField(
            model_name='cteprestacaoservico',
            name='valor_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor a Receber'),
        ),
        migrations.AlterField(
            model_name='cteprestacaoservico',
            name='valor_total_prestado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Total Prestação'),
        ),
        migrations.AlterField(
            model_name='cterecebedor',
            name='razao_social',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Razão Social/Nome'),
        ),
        migrations.AlterField(
            model_name='cteremetente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Razão Social/Nome'),
        ),
        migrations.AlterField(
            model_name='cteseguro',
            name='nome_seguradora',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome Seguradora'),
        ),
        migrations.AlterField(
            model_name='cteseguro',
            name='numero_apolice',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Apólice'),
        ),
        migrations.AlterField(
            model_name='mdfeemitente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Razão Social/Nome'),
        ),
        migrations.AlterField(
            model_name='mdfeprodutopredominante',
            name='tp_carga',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tipo Carga'),
        ),
        migrations.AlterField(
            model_name='mdfeprodutopredominante',
            name='x_prod',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Descrição Produto'),
        ),
        migrations.AlterField(
            model_name='mdfesegurocarga',
            name='cnpj_seguradora',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ Seguradora'),
        ),
        migrations.AlterField(
            model_name='mdfesegurocarga',
            name='nome_seguradora',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome Seguradora'),
        ),
        migrations.AlterField(
            model_name='mdfesegurocarga',
            name='numero_apolice',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Apólice'),
        ),
        migrations.AlterField(
            model_name='mdfetotais',
            name='c_unid',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Código Unidade Peso Bruto'),
        ),
        migrations.AlterField(
            model_name='mdfetotais',
            name='q_carga',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Peso Bruto Total Carga'),
        ),
        migrations.AlterField(
            model_name='mdfetotais',
            name='v_carga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Total Carga'),
        ),
    ]
