# Generated by Django 5.2.9 on 2026-06-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0020_faseA_nullable_remover_masking_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cteseguro',
            name='responsavel',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Responsável Seguro'),
        ),
        migrations.AlterField(
            model_name='cteseguro',
            name='valor_carga_averbada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Carga (Averbação)'),
        ),
        migrations.AlterField(
            model_name='mdfesegurocarga',
            name='responsavel',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Responsável Seguro'),
        ),
    ]
