# Generated by Django 5.2.9 on 2026-06-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0021_faseA_nullable_seguro_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctetributos',
            name='icms_cst',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='CST ICMS'),
        ),
        migrations.AddField(
            model_name='ctetributos',
            name='icms_picms',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Alíquota ICMS'),
        ),
        migrations.AddField(
            model_name='ctetributos',
            name='icms_picms_st',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Alíquota ICMS ST'),
        ),
        migrations.AddField(
            model_name='ctetributos',
            name='icms_pred_bc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='% Redução Base ICMS'),
        ),
        migrations.AddField(
            model_name='ctetributos',
            name='icms_tipo',
            field=models.CharField(blank=True, help_text='ICMS00/20/45/60/90/OutraUF/SN', max_length=12, null=True, verbose_name='Grupo ICMS'),
        ),
        migrations.AddField(
            model_name='ctetributos',
            name='icms_uffim',
            field=models.JSONField(blank=True, null=True, verbose_name='ICMS UF Fim (partilha)'),
        ),
        migrations.AddField(
            model_name='ctetributos',
            name='icms_vbc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Base de Cálculo ICMS'),
        ),
        migrations.AddField(
            model_name='ctetributos',
            name='icms_vbc_st',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Base de Cálculo ICMS ST'),
        ),
        migrations.AddField(
            model_name='ctetributos',
            name='icms_vcred',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Crédito ICMS (SN)'),
        ),
        migrations.AddField(
            model_name='ctetributos',
            name='icms_vicms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor ICMS'),
        ),
        migrations.AddField(
            model_name='ctetributos',
            name='icms_vicms_st',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor ICMS ST'),
        ),
        migrations.AlterField(
            model_name='ctetributos',
            name='icms',
            field=models.JSONField(blank=True, help_text='Estrutura JSON bruta do ICMS aplicável.', null=True, verbose_name='Detalhes ICMS (bruto)'),
        ),
    ]
