# Generated by Django 5.2.9 on 2026-06-14 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0022_faseB_cte_icms_detalhado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctemodalrodoviario',
            name='ciot',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='CIOT'),
        ),
        migrations.AddField(
            model_name='cteseguro',
            name='valor_seguro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor do Seguro'),
        ),
        migrations.AlterField(
            model_name='ctemodalrodoviario',
            name='rntrc',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='RNTRC'),
        ),
        migrations.CreateModel(
            name='CTeCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fatura', models.CharField(blank=True, max_length=60, null=True, verbose_name='Número Fatura')),
                ('valor_original', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Original')),
                ('valor_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Desconto')),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Líquido')),
                ('cte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cobranca', to='transport.ctedocumento')),
            ],
            options={
                'verbose_name': 'CT-e – Cobrança',
                'verbose_name_plural': 'CT-e – Cobrança',
                'db_table': 'cte_cobranca',
            },
        ),
        migrations.CreateModel(
            name='CTeDuplicata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=60, null=True, verbose_name='Número Duplicata')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Duplicata')),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicatas', to='transport.ctecobranca')),
            ],
            options={
                'verbose_name': 'CT-e – Duplicata',
                'verbose_name_plural': 'CT-e – Duplicatas',
                'db_table': 'cte_duplicata',
            },
        ),
        migrations.CreateModel(
            name='CTeFluxoPassagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_passagem', models.CharField(blank=True, max_length=15, null=True, verbose_name='Sigla/Nome Passagem')),
                ('ordem', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ordem')),
                ('cte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxo_passagens', to='transport.ctedocumento')),
            ],
            options={
                'verbose_name': 'CT-e – Fluxo (Passagem)',
                'verbose_name_plural': 'CT-e – Fluxo (Passagens)',
                'db_table': 'cte_fluxo_passagem',
            },
        ),
        migrations.CreateModel(
            name='CTeOrdemColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=3, null=True, verbose_name='Série OC')),
                ('numero', models.CharField(blank=True, max_length=9, null=True, verbose_name='Número OC')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data Emissão OC')),
                ('cnpj_emissor', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ Emissor OC')),
                ('cpf_emissor', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF Emissor OC')),
                ('telefone_emissor', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone Emissor OC')),
                ('modal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_coleta', to='transport.ctemodalrodoviario')),
            ],
            options={
                'verbose_name': 'CT-e – Ordem de Coleta',
                'verbose_name_plural': 'CT-e – Ordens de Coleta',
                'db_table': 'cte_ordem_coleta',
            },
        ),
        migrations.CreateModel(
            name='CTeValePedagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_fornecedor', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ Fornecedor')),
                ('cnpj_responsavel', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ Responsável Pgto')),
                ('cpf_responsavel', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF Responsável Pgto')),
                ('numero_comprovante', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº Comprovante')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Vale-Pedágio')),
                ('tipo_vale', models.CharField(blank=True, max_length=2, null=True, verbose_name='Tipo Vale')),
                ('cte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales_pedagio', to='transport.ctedocumento')),
            ],
            options={
                'verbose_name': 'CT-e – Vale-Pedágio',
                'verbose_name_plural': 'CT-e – Vales-Pedágio',
                'db_table': 'cte_vale_pedagio',
            },
        ),
    ]
