# Generated by Django 5.2.9 on 2026-06-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0023_faseB_cte_cobranca_valeped_ciot_fluxo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdfemodalrodoviario',
            name='id_ac',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='ID Agenciador de Cargas (AC)'),
        ),
        migrations.AddField(
            model_name='mdfemodalrodoviario',
            name='id_tac',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='ID Transportador Autônomo (TAC)'),
        ),
        migrations.AddField(
            model_name='mdfemodalrodoviario',
            name='nro_ocrim',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº Ocorrência Criminal'),
        ),
        migrations.AddField(
            model_name='mdfemodalrodoviario',
            name='nro_proc',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nº Processo Administrativo'),
        ),
        migrations.AddField(
            model_name='mdfemodalrodoviario',
            name='tp_rntrc',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tipo RNTRC'),
        ),
        migrations.AddField(
            model_name='mdfemodalrodoviario',
            name='val_apagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor a Pagar Total'),
        ),
        migrations.AddField(
            model_name='mdfemodalrodoviario',
            name='val_etarifa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor E-Tarifa ANTT'),
        ),
        migrations.AddField(
            model_name='mdfemodalrodoviario',
            name='val_resp_frete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Repasse Responsável Frete'),
        ),
        migrations.AddField(
            model_name='mdfeprodutoperigoso',
            name='ponto_fulgor',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Ponto de Fulgor'),
        ),
        migrations.AddField(
            model_name='mdfetotais',
            name='q_unid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtd. Unidades de Carga'),
        ),
        migrations.AlterField(
            model_name='mdfeprodutoperigoso',
            name='n_onu',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Número ONU'),
        ),
        migrations.AlterField(
            model_name='mdfeprodutoperigoso',
            name='q_tot_prod',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Quantidade Total Produto'),
        ),
    ]
