# Generated by Django 5.2.9 on 2026-06-14 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0024_faseC_mdfe_antt_pontofulgor_qunid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdfeprodutopredominante',
            name='cep_carrega',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP Local Carregamento'),
        ),
        migrations.AddField(
            model_name='mdfeprodutopredominante',
            name='cep_descarrega',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP Local Descarregamento'),
        ),
        migrations.AddField(
            model_name='mdfeprodutopredominante',
            name='lat_carrega',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Latitude Carregamento'),
        ),
        migrations.AddField(
            model_name='mdfeprodutopredominante',
            name='lat_descarrega',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Latitude Descarregamento'),
        ),
        migrations.AddField(
            model_name='mdfeprodutopredominante',
            name='long_carrega',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Longitude Carregamento'),
        ),
        migrations.AddField(
            model_name='mdfeprodutopredominante',
            name='long_descarrega',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Longitude Descarregamento'),
        ),
        migrations.CreateModel(
            name='MDFeObservacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cont', 'Contribuinte'), ('fisco', 'Fisco')], max_length=5, verbose_name='Tipo')),
                ('campo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificação Campo')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Conteúdo')),
                ('mdfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='transport.mdfedocumento')),
            ],
            options={
                'verbose_name': 'MDF-e – Observação',
                'verbose_name_plural': 'MDF-e – Observações',
                'db_table': 'mdfe_observacao',
            },
        ),
    ]
