# Generated by Django 5.2.9 on 2026-06-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0025_faseC_mdfe_inflotacao_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctedocumentotransportado',
            name='data_prevista_nf',
            field=models.DateField(blank=True, null=True, verbose_name='Data Prevista Entrega NF'),
        ),
        migrations.AddField(
            model_name='ctedocumentotransportado',
            name='unidades_transporte',
            field=models.JSONField(blank=True, null=True, verbose_name='Unidades de Transporte/Carga'),
        ),
        migrations.AddField(
            model_name='mdfedocumentosvinculados',
            name='unidades_transporte',
            field=models.JSONField(blank=True, null=True, verbose_name='Unidades de Transporte/Carga'),
        ),
    ]
