# Generated by Django 5.2.9 on 2026-06-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0026_faseC_unidades_transporte_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdfeciot',
            name='ciot',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='CIOT'),
        ),
    ]
