# Generated by Django 5.2.9 on 2026-06-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0028_gaps_recepcao_modais_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctemotorista',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctes_como_condutor', to='transport.motorista'),
        ),
        migrations.AddField(
            model_name='mdfecondutor',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mdfes_como_condutor', to='transport.motorista'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='cadastro_automatico',
            field=models.BooleanField(default=False, help_text='Criado automaticamente a partir de um condutor de CT-e/MDF-e; pode estar incompleto (sem CNH/validades).', verbose_name='Cadastro automático (via XML)'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cnh',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='CNH'),
        ),
    ]
