# Generated by Django 5.2.9 on 2026-06-18 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0029_auto_cadastro_motorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentoproprio',
            name='cte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamento_proprio', to='transport.ctedocumento', verbose_name='CT-e Vinculado'),
        ),
    ]
