# Generated by Django 5.2.9 on 2026-06-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0030_pagamento_proprio_cte_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctedocumento',
            name='caminho_arquivo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho do Arquivo'),
        ),
        migrations.AddField(
            model_name='ctedocumento',
            name='checksum',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Checksum SHA-256'),
        ),
        migrations.AddField(
            model_name='ctedocumento',
            name='data_arquivamento',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Arquivamento'),
        ),
        migrations.AddField(
            model_name='mdfedocumento',
            name='caminho_arquivo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho do Arquivo'),
        ),
        migrations.AddField(
            model_name='mdfedocumento',
            name='checksum',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Checksum SHA-256'),
        ),
        migrations.AddField(
            model_name='mdfedocumento',
            name='data_arquivamento',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Arquivamento'),
        ),
    ]
