# Generated by Django 5.0 on 2026-06-20 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0031_adicionar_retencao_xmls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleNumeracao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj_emitente', models.CharField(db_index=True, max_length=14, verbose_name='CNPJ Emitente')),
                ('modelo', models.CharField(choices=[('CTe', 'CT-e'), ('MDFe', 'MDF-e')], db_index=True, max_length=4, verbose_name='Modelo')),
                ('serie', models.CharField(db_index=True, max_length=5, verbose_name='Série')),
                ('ultimo_numero', models.PositiveIntegerField(default=0, verbose_name='Último Número')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Controle de Numeração',
                'verbose_name_plural': 'Controles de Numeração',
                'db_table': 'controle_numeracao',
                'constraints': [models.UniqueConstraint(fields=('cnpj_emitente', 'modelo', 'serie'), name='unique_controle_numeracao')],
            },
        ),
    ]
