# Generated by Django 5.2.9 on 2026-06-20 17:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0032_add_controle_numeracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('combustivel', 'Combustível'), ('pedagio', 'Pedágio'), ('seguro', 'Seguro'), ('oficina', 'Oficina'), ('outras', 'Outras')], default='outras', max_length=20, verbose_name='Categoria')),
                ('fornecedor', models.CharField(blank=True, max_length=120, null=True, verbose_name='Fornecedor')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], db_index=True, default='pendente', max_length=10, verbose_name='Status')),
                ('comprovante', models.FileField(blank=True, help_text='Comprovante de pagamento (PDF, imagem)', null=True, upload_to='comprovantes/contas_pagar/%Y/%m/', verbose_name='Comprovante')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_pagar', to='transport.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'db_table': 'conta_pagar',
                'ordering': ['-data_vencimento', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60, unique=True, verbose_name='Número')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('data_emissao', models.DateField(default=datetime.date.today, verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas', to='transport.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'db_table': 'fatura',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=10, verbose_name='Tipo')),
                ('arquivo_origem', models.CharField(max_length=255, verbose_name='Arquivo de Origem')),
                ('conciliado', models.BooleanField(default=False, verbose_name='Conciliado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='transport.contapagar', verbose_name='Conta a Pagar')),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='transport.fatura', verbose_name='Fatura')),
            ],
            options={
                'verbose_name': 'Transação Bancária',
                'verbose_name_plural': 'Transações Bancárias',
                'db_table': 'transacao_bancaria',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
