# Generated by Django 5.2.9 on 2026-06-20 18:08

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0034_add_faturas'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemViagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número OS')),
                ('tipo', models.CharField(choices=[('carga', 'Carga'), ('descarga', 'Descarga'), ('transferencia', 'Transferência'), ('outros', 'Outros')], default='carga', max_length=15, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], db_index=True, default='rascunho', max_length=15, verbose_name='Status')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Saída')),
                ('data_retorno', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Retorno')),
                ('data_previsao_chegada', models.DateTimeField(blank=True, null=True, verbose_name='Previsão Chegada')),
                ('km_inicial', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM Inicial')),
                ('km_final', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM Final')),
                ('origem_uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Origem')),
                ('origem_cidade', models.CharField(blank=True, max_length=120, null=True, verbose_name='Cidade Origem')),
                ('destino_uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Destino')),
                ('destino_cidade', models.CharField(blank=True, max_length=120, null=True, verbose_name='Cidade Destino')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_viagem', to='transport.cliente', verbose_name='Cliente')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_viagem', to='transport.motorista', verbose_name='Motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_viagem', to='transport.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Ordem de Viagem',
                'verbose_name_plural': 'Ordens de Viagem',
                'db_table': 'ordem_viagem',
                'ordering': ['-data_saida', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DespesaViagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('pedagio', 'Pedágio'), ('alimentacao', 'Alimentação'), ('hospedagem', 'Hospedagem'), ('manutencao', 'Manutenção'), ('outros', 'Outros')], default='outros', max_length=15, verbose_name='Categoria')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/despesas_viagem/%Y/%m/', verbose_name='Comprovante')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='transport.ordemviagem')),
            ],
            options={
                'verbose_name': 'Despesa de Viagem',
                'verbose_name_plural': 'Despesas de Viagem',
                'db_table': 'despesa_viagem',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OrdemViagemCTe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_entrega', models.PositiveSmallIntegerField(default=1, verbose_name='Ordem de Entrega')),
                ('cte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_viagem', to='transport.ctedocumento')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctes', to='transport.ordemviagem')),
            ],
            options={
                'verbose_name': 'CT-e da Ordem',
                'verbose_name_plural': 'CT-es da Ordem',
                'db_table': 'ordem_viagem_cte',
                'ordering': ['ordem_entrega', 'cte__identificacao__numero'],
            },
        ),
        migrations.CreateModel(
            name='OrdemViagemParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('coleta', 'Coleta'), ('entrega', 'Entrega'), ('parada', 'Parada'), ('outros', 'Outros')], default='parada', max_length=10, verbose_name='Tipo')),
                ('sequencia', models.PositiveSmallIntegerField(default=1, verbose_name='Sequência')),
                ('cidade', models.CharField(blank=True, max_length=120, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('data_previsao', models.DateTimeField(blank=True, null=True, verbose_name='Previsão')),
                ('data_realizada', models.DateTimeField(blank=True, null=True, verbose_name='Realizada')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='transport.ordemviagem')),
            ],
            options={
                'verbose_name': 'Parada da Ordem',
                'verbose_name_plural': 'Paradas da Ordem',
                'db_table': 'ordem_viagem_parada',
                'ordering': ['sequencia'],
            },
        ),
        migrations.AddIndex(
            model_name='ordemviagem',
            index=models.Index(fields=['status', 'data_saida'], name='ordem_viage_status_7a7a37_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemviagem',
            index=models.Index(fields=['veiculo', 'status'], name='ordem_viage_veiculo_21ccce_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemviagem',
            index=models.Index(fields=['motorista', 'status'], name='ordem_viage_motoris_c90a96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ordemviagemcte',
            unique_together={('ordem', 'cte')},
        ),
    ]
