# Generated by Django 5.2.9 on 2026-06-20 18:19

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0035_ordens_viagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Data')),
                ('hodometro', models.PositiveIntegerField(verbose_name='Hodômetro (KM)')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total (R$)')),
                ('tipo_combustivel', models.CharField(choices=[('diesel', 'Diesel'), ('diesel_s10', 'Diesel S10'), ('arla', 'Arla 32'), ('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('gnv', 'GNV'), ('outros', 'Outros')], default='diesel', max_length=15, verbose_name='Tipo de Combustível')),
                ('posto', models.CharField(blank=True, max_length=120, null=True, verbose_name='Posto/Fornecedor')),
                ('cnpj_posto', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ Posto')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/abastecimentos/%Y/%m/', verbose_name='Comprovante')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='transport.motorista', verbose_name='Motorista')),
                ('ordem_viagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to='transport.ordemviagem', verbose_name='Ordem de Viagem')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='transport.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'db_table': 'abastecimento',
                'ordering': ['-data', '-criado_em'],
                'indexes': [models.Index(fields=['veiculo', 'data'], name='abastecimen_veiculo_47a487_idx'), models.Index(fields=['tipo_combustivel', 'data'], name='abastecimen_tipo_co_dcc59e_idx')],
            },
        ),
    ]
