# Generated by Django 5.2.9 on 2026-06-20 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0036_abastecimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoManutencao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('preditiva', 'Preditiva')], default='preventiva', max_length=15, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Serviço')),
                ('intervalo_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Intervalo (KM)')),
                ('intervalo_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Intervalo (Dias)')),
                ('ultima_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Última KM Realizada')),
                ('ultima_data', models.DateField(blank=True, null=True, verbose_name='Última Data Realizada')),
                ('proxima_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Próxima KM')),
                ('proxima_data', models.DateField(blank=True, null=True, verbose_name='Próxima Data')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_manutencao', to='transport.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Plano de Manutenção',
                'verbose_name_plural': 'Planos de Manutenção',
                'db_table': 'plano_manutencao',
                'ordering': ['veiculo__placa', 'tipo', 'descricao'],
            },
        ),
    ]
