# Generated by Django 5.2.9 on 2026-06-20 18:29

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0037_plano_manutencao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_infracao', models.DateField(default=datetime.date.today, verbose_name='Data da Infração')),
                ('local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição/Infração')),
                ('auto_infracao', models.CharField(blank=True, max_length=30, null=True, verbose_name='Auto de Infração')),
                ('gravidade', models.CharField(choices=[('leve', 'Leve'), ('media', 'Média'), ('grave', 'Grave'), ('gravissima', 'Gravíssima')], default='media', max_length=15, verbose_name='Gravidade')),
                ('pontos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pontos')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('impugnada', 'Impugnada'), ('cancelada', 'Cancelada')], db_index=True, default='pendente', max_length=15, verbose_name='Status')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/multas/%Y/%m/', verbose_name='Comprovante')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='transport.motorista', verbose_name='Motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='transport.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'db_table': 'multa',
                'ordering': ['-data_infracao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Sinistro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local')),
                ('tipo', models.CharField(choices=[('colisao', 'Colisão'), ('incendio', 'Incêndio'), ('furto_roubo', 'Furto/Roubo'), ('avaria_carga', 'Avaria de Carga'), ('outros', 'Outros')], default='colisao', max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('envolvidos_terceiros', models.TextField(blank=True, null=True, verbose_name='Envolvidos / Terceiros')),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo Total (R$)')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado')], db_index=True, default='aberto', max_length=15, verbose_name='Status')),
                ('numero_sinistro', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número do Sinistro')),
                ('seguradora', models.CharField(blank=True, max_length=120, null=True, verbose_name='Seguradora')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/sinistros/%Y/%m/', verbose_name='Comprovante/Boletim')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sinistros', to='transport.motorista', verbose_name='Motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sinistros', to='transport.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Sinistro',
                'verbose_name_plural': 'Sinistros',
                'db_table': 'sinistro',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
