# Generated by Django 5.2.9 on 2026-06-20 18:34

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0038_multas_sinistros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedagio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('praca', models.CharField(max_length=120, verbose_name='Praça/Pedágio')),
                ('rodovia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rodovia/BR')),
                ('km', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM')),
                ('categoria', models.CharField(blank=True, max_length=10, null=True, verbose_name='Categoria')),
                ('tag', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tag/Passagem')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/pedagios/%Y/%m/', verbose_name='Comprovante')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ordem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedagios', to='transport.ordemviagem', verbose_name='Ordem de Viagem')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedagios', to='transport.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Pedágio',
                'verbose_name_plural': 'Pedágios',
                'db_table': 'pedagio',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
