# Generated by Django 5.2.9 on 2026-06-20 18:40

import datetime
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0039_pedagio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaFrete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origem_uf', models.CharField(max_length=2, verbose_name='UF Origem')),
                ('origem_cidade', models.CharField(max_length=120, verbose_name='Cidade Origem')),
                ('destino_uf', models.CharField(max_length=2, verbose_name='UF Destino')),
                ('destino_cidade', models.CharField(max_length=120, verbose_name='Cidade Destino')),
                ('tipo_veiculo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Veículo')),
                ('valor_por_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor por KM (R$)')),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Mínimo (R$)')),
                ('valor_tonelada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor por Tonelada (R$)')),
                ('valor_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor por M³ (R$)')),
                ('vigencia_inicio', models.DateField(default=datetime.date.today, verbose_name='Início Vigência')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Fim Vigência')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tabela de Frete',
                'verbose_name_plural': 'Tabelas de Frete',
                'db_table': 'tabela_frete',
                'ordering': ['origem_uf', 'origem_cidade', 'destino_uf', 'destino_cidade'],
                'indexes': [models.Index(fields=['origem_uf', 'destino_uf'], name='tabela_fret_origem__8af991_idx'), models.Index(fields=['ativo', 'vigencia_inicio', 'vigencia_fim'], name='tabela_fret_ativo_07ca5c_idx')],
            },
        ),
    ]
