# Generated by Django 5.2.9 on 2026-06-20 18:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0040_tabela_frete'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicaoVeiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude')),
                ('velocidade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Velocidade (km/h)')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('fonte', models.CharField(choices=[('manual', 'Manual'), ('gps', 'GPS'), ('app', 'App Motorista')], default='manual', max_length=10, verbose_name='Fonte')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='transport.ordemviagem', verbose_name='Ordem de Viagem')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posicoes', to='transport.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Posição do Veículo',
                'verbose_name_plural': 'Posições dos Veículos',
                'db_table': 'posicao_veiculo',
                'ordering': ['-data_hora'],
            },
        ),
    ]
