# Generated by Django 5.2.9 on 2026-06-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0041_posicao_veiculo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ctedocumento',
            index=models.Index(fields=['pago', 'data_pagamento'], name='cte_documen_pago_3e9747_idx'),
        ),
        migrations.AddIndex(
            model_name='ctedocumento',
            index=models.Index(fields=['pago', 'data_upload'], name='cte_documen_pago_7435be_idx'),
        ),
        migrations.AddIndex(
            model_name='cteidentificacao',
            index=models.Index(fields=['numero', 'serie'], name='cte_identif_numero_46a6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='cteidentificacao',
            index=models.Index(fields=['uf_ini', 'uf_fim'], name='cte_identif_uf_ini_6964cf_idx'),
        ),
        migrations.AddIndex(
            model_name='cteidentificacao',
            index=models.Index(fields=['data_emissao', 'numero'], name='cte_identif_data_em_53c01a_idx'),
        ),
        migrations.AddIndex(
            model_name='mdfedocumento',
            index=models.Index(fields=['processado', 'data_upload'], name='mdfe_docume_process_e6e014_idx'),
        ),
        migrations.AddIndex(
            model_name='mdfedocumento',
            index=models.Index(fields=['encerrado', 'data_encerramento'], name='mdfe_docume_encerra_bd651a_idx'),
        ),
        migrations.AddIndex(
            model_name='mdfeidentificacao',
            index=models.Index(fields=['n_mdf', 'serie'], name='mdfe_identi_n_mdf_fcd7f0_idx'),
        ),
        migrations.AddIndex(
            model_name='mdfeidentificacao',
            index=models.Index(fields=['uf_ini', 'uf_fim'], name='mdfe_identi_uf_ini_8f78af_idx'),
        ),
        migrations.AddIndex(
            model_name='mdfeidentificacao',
            index=models.Index(fields=['dh_emi', 'n_mdf'], name='mdfe_identi_dh_emi_8e650a_idx'),
        ),
    ]
