# Generated by Django 5.2.9 on 2026-06-20 23:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0042_indices_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemviagem',
            name='destino_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude Destino'),
        ),
        migrations.AddField(
            model_name='ordemviagem',
            name='destino_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude Destino'),
        ),
        migrations.AddField(
            model_name='ordemviagem',
            name='origem_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude Origem'),
        ),
        migrations.AddField(
            model_name='ordemviagem',
            name='origem_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude Origem'),
        ),
        migrations.AddField(
            model_name='ordemviagemparada',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='ordemviagemparada',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude'),
        ),
        migrations.CreateModel(
            name='RotaOtimizada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Distância (km)')),
                ('duracao_min', models.IntegerField(verbose_name='Duração (min)')),
                ('geometria', models.JSONField(blank=True, null=True, verbose_name='Geometria (GeoJSON)')),
                ('waypoints', models.JSONField(blank=True, null=True, verbose_name='Waypoints ordenados')),
                ('provedor', models.CharField(default='osrm', max_length=50, verbose_name='Provedor')),
                ('status', models.CharField(choices=[('calculada', 'Calculada'), ('em_uso', 'Em Uso'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='calculada', max_length=15, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='transport.ordemviagem', verbose_name='Ordem de Viagem')),
            ],
            options={
                'verbose_name': 'Rota Otimizada',
                'verbose_name_plural': 'Rotas Otimizadas',
                'db_table': 'rota_otimizada',
                'ordering': ['-criado_em'],
            },
        ),
    ]
