# Generated by Django 5.2.9 on 2026-06-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0043_rota_otimizada_e_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='gps_identificador',
            field=models.CharField(blank=True, help_text='Identificador do veículo no sistema de rastreamento GPS', max_length=60, null=True, verbose_name='ID no GPS'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='gps_provedor',
            field=models.CharField(blank=True, help_text='Ex: onixsat, sitrack, autotrac, sascar', max_length=30, null=True, verbose_name='Provedor GPS'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='gps_ultima_sincronizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização GPS'),
        ),
    ]
