# Generated by Django 5.2.9 on 2026-06-20 23:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0044_veiculo_gps'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemComunicacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=10, verbose_name='Canal')),
                ('destinatario', models.CharField(max_length=255, verbose_name='Destinatário')),
                ('assunto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Assunto')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('falha', 'Falha')], default='pendente', max_length=10, verbose_name='Status')),
                ('erro', models.TextField(blank=True, null=True, verbose_name='Erro')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicacoes', to='transport.cliente', verbose_name='Cliente')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicacoes', to='transport.motorista', verbose_name='Motorista')),
                ('ordem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicacoes', to='transport.ordemviagem', verbose_name='Ordem de Viagem')),
            ],
            options={
                'verbose_name': 'Mensagem de Comunicação',
                'verbose_name_plural': 'Mensagens de Comunicação',
                'db_table': 'mensagem_comunicacao',
                'ordering': ['-criado_em'],
            },
        ),
    ]
