# Generated by Django 5.2.9 on 2026-06-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0045_mensagem_comunicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertasistema',
            name='data_resolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Resolução'),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='lido',
            field=models.BooleanField(default=False, verbose_name='Lido'),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='resolvido',
            field=models.BooleanField(default=False, verbose_name='Resolvido'),
        ),
        migrations.AddField(
            model_name='ctedocumento',
            name='status',
            field=models.CharField(choices=[('autorizado', 'Autorizado'), ('cancelado', 'Cancelado'), ('encerrado', 'Encerrado'), ('denegado', 'Denegado'), ('inutilizado', 'Inutilizado')], db_index=True, default='autorizado', max_length=15, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='mdfedocumento',
            name='status',
            field=models.CharField(choices=[('autorizado', 'Autorizado'), ('cancelado', 'Cancelado'), ('encerrado', 'Encerrado'), ('denegado', 'Denegado'), ('inutilizado', 'Inutilizado')], db_index=True, default='autorizado', max_length=15, verbose_name='Status'),
        ),
    ]
