# Generated by Django 5.2.9 on 2026-06-21 02:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0046_status_campo_alertas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIOT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, help_text='Código de 12 dígitos numéricos gerado no sistema CIOT/NTT', max_length=12, unique=True, verbose_name='Código CIOT')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('responsavel_cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ Responsável')),
                ('responsavel_cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF Responsável')),
                ('origem_cidade', models.CharField(blank=True, max_length=120, null=True, verbose_name='Cidade Origem')),
                ('origem_uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Origem')),
                ('destino_cidade', models.CharField(blank=True, max_length=120, null=True, verbose_name='Cidade Destino')),
                ('destino_uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Destino')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor da Operação')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('usado', 'Usado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], db_index=True, default='ativo', max_length=10, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciots', to='transport.cliente', verbose_name='Contratante')),
                ('cte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciots', to='transport.ctedocumento', verbose_name='CT-e Vinculado')),
                ('mdfe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciots', to='transport.mdfedocumento', verbose_name='MDF-e Vinculado')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciots', to='transport.motorista', verbose_name='Contratado / Motorista')),
                ('ordem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciots', to='transport.ordemviagem', verbose_name='Ordem de Viagem')),
            ],
            options={
                'verbose_name': 'CIOT',
                'verbose_name_plural': 'CIOTs',
                'db_table': 'ciot',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'data_validade'], name='ciot_status_4f7923_idx'), models.Index(fields=['cliente', 'status'], name='ciot_cliente_b99a2b_idx'), models.Index(fields=['motorista', 'status'], name='ciot_motoris_2201f8_idx')],
            },
        ),
    ]
