# Generated by Django 5.2.9 on 2026-06-21 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0047_ciot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemviagem',
            name='ciot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_viagem', to='transport.ciot', verbose_name='CIOT'),
        ),
    ]
