# Generated by Django 5.2.9 on 2026-06-25 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0048_ordem_viagem_ciot'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='laudo_vistoria_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Laudo de Vistoria - Validade'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='seguro_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Seguro - Validade'),
        ),
        migrations.AlterField(
            model_name='posicaoveiculo',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora'),
        ),
    ]
