# Generated by Django 5.2.9 on 2026-06-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0050_limpar_dist_km_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoempresa',
            name='telefone_financeiro',
            field=models.CharField(blank=True, help_text='Recebe notificações de cobranças e faturamentos', max_length=20, null=True, verbose_name='Telefone do Financeiro'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='telefone_gestor',
            field=models.CharField(blank=True, help_text='Recebe notificações de pagamentos e alertas críticos', max_length=20, null=True, verbose_name='Telefone do Gestor'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='telefone_operacional',
            field=models.CharField(blank=True, help_text='Recebe notificações de manutenções e vencimentos', max_length=20, null=True, verbose_name='Telefone do Operacional'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='agencia',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Chave Pix'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='favorecido',
            field=models.CharField(blank=True, help_text='Nome do titular da conta, se diferente do motorista', max_length=255, null=True, verbose_name='Favorecido'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='tipo_chave_pix',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('celular', 'Celular'), ('email', 'E-mail'), ('aleatoria', 'Chave Aleatória')], max_length=10, null=True, verbose_name='Tipo de Chave Pix'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='tipo_conta',
            field=models.CharField(blank=True, choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança'), ('salario', 'Salário')], max_length=10, null=True, verbose_name='Tipo de Conta'),
        ),
    ]
