# Generated by Django 5.2.9 on 2026-08-27 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_valor_frete_importado(apps, schema_editor):
    cte_documento = apps.get_model('transport', 'CTeDocumento')
    prestacao = apps.get_model('transport', 'CTePrestacaoServico')
    valor_importado = prestacao.objects.filter(
        cte_id=OuterRef('pk')
    ).values('valor_total_prestado')[:1]
    cte_documento.objects.update(
        valor_frete_importado=Subquery(valor_importado)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0051_add_pix_e_telefones_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctedocumento',
            options={'ordering': ['-identificacao__data_emissao'], 'permissions': [('editar_valor_frete_cte', 'Pode editar manualmente o valor de frete do CT-e'), ('excluir_cte_importado', 'Pode excluir CT-e importado')], 'verbose_name': 'CT-e (Documento)', 'verbose_name_plural': 'CT-e (Documentos)'},
        ),
        migrations.AddField(
            model_name='ctedocumento',
            name='valor_frete_editado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctedocumento',
            name='valor_frete_editado_manualmente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ctedocumento',
            name='valor_frete_editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctes_com_valor_editado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ctedocumento',
            name='valor_frete_importado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Último valor recebido do XML/EGS, preservado para auditoria.', max_digits=15, null=True, verbose_name='Valor de Frete Importado'),
        ),
        migrations.RunPython(backfill_valor_frete_importado, migrations.RunPython.noop),
    ]
