# Generated by Django 5.2.9 on 2026-09-04 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


PERFIS_GERENCIADOS = {'Leitura', 'Operacional', 'Financeiro', 'Administrativo'}

PERMISSOES_ESPECIAIS = {
    'visualizar_inadimplencia': 'Pode visualizar inadimplência',
    'visualizar_fluxo_caixa': 'Pode visualizar fluxo de caixa',
    'visualizar_dre': 'Pode visualizar DRE',
    'enviar_comunicacao': 'Pode enviar comunicações',
    'testar_comunicacao': 'Pode testar integrações de comunicação',
    'visualizar_posicao_gps': 'Pode visualizar posição GPS',
    'visualizar_relatorios': 'Pode visualizar relatórios',
    'visualizar_dashboard_geral': 'Pode visualizar dashboard geral',
    'visualizar_dashboard_cte': 'Pode visualizar painel de CT-e',
    'visualizar_dashboard_mdfe': 'Pode visualizar painel de MDF-e',
    'visualizar_dashboard_financeiro': 'Pode visualizar painel financeiro',
    'visualizar_dashboard_frota': 'Pode visualizar painel de frota',
    'gerenciar_acessos_usuarios': 'Pode gerenciar usuários, perfis e permissões de acesso',
}


def preparar_permissoes_especiais(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    content_type, _ = ContentType.objects.get_or_create(
        app_label='transport', model='configuracaoacessousuario',
    )
    permissions = {}
    for codename, name in PERMISSOES_ESPECIAIS.items():
        permission, _ = Permission.objects.get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={'name': name},
        )
        permissions[codename] = permission

    for group in Group.objects.filter(name__in=PERFIS_GERENCIADOS):
        existing = set(group.permissions.values_list('codename', flat=True))
        # Dashboard/relatórios já eram abertos a qualquer autenticado. As demais
        # ações são adicionadas somente se o grupo já possuía a permissão-base.
        codenames = {'visualizar_dashboard_geral', 'visualizar_relatorios'}
        if 'view_ctedocumento' in existing:
            codenames.add('visualizar_dashboard_cte')
        if 'view_mdfedocumento' in existing:
            codenames.add('visualizar_dashboard_mdfe')
        if existing & {'view_fatura', 'view_contapagar', 'view_pagamentoagregado'}:
            codenames.update({
                'visualizar_inadimplencia', 'visualizar_fluxo_caixa',
                'visualizar_dre', 'visualizar_dashboard_financeiro',
            })
        if existing & {'view_veiculo', 'view_posicaoveiculo', 'view_manutencaoveiculo'}:
            codenames.update({'visualizar_posicao_gps', 'visualizar_dashboard_frota'})
        if 'add_mensagemcomunicacao' in existing:
            codenames.add('enviar_comunicacao')
        if 'change_mensagemcomunicacao' in existing:
            codenames.add('testar_comunicacao')
        group.permissions.add(*(permissions[name] for name in codenames))


def criar_configuracoes_existentes(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Configuracao = apps.get_model('transport', 'ConfiguracaoAcessoUsuario')
    configuracoes = []
    for user in User.objects.prefetch_related('groups').iterator(chunk_size=200):
        perfis = [group.name for group in user.groups.all() if group.name in PERFIS_GERENCIADOS]
        modo = 'perfil' if len(perfis) == 1 and not user.is_superuser else 'personalizado'
        configuracoes.append(Configuracao(
            usuario_id=user.pk,
            modo=modo,
            perfil_base=perfis[0] if modo == 'perfil' else '',
        ))
    Configuracao.objects.bulk_create(configuracoes, ignore_conflicts=True)


def remover_configuracoes_existentes(apps, schema_editor):
    apps.get_model('transport', 'ConfiguracaoAcessoUsuario').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0052_cte_admin_manual_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAcessoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('perfil', 'Perfil'), ('personalizado', 'Personalizado')], default='perfil', max_length=20)),
                ('perfil_base', models.CharField(blank=True, default='', max_length=50)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_acesso_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de acesso do usuário',
                'verbose_name_plural': 'Configurações de acesso dos usuários',
                'db_table': 'configuracao_acesso_usuario',
                'permissions': [('gerenciar_acessos_usuarios', 'Pode gerenciar usuários, perfis e permissões de acesso'), ('visualizar_inadimplencia', 'Pode visualizar inadimplência'), ('visualizar_fluxo_caixa', 'Pode visualizar fluxo de caixa'), ('visualizar_dre', 'Pode visualizar DRE'), ('enviar_comunicacao', 'Pode enviar comunicações'), ('testar_comunicacao', 'Pode testar integrações de comunicação'), ('visualizar_posicao_gps', 'Pode visualizar posição GPS'), ('visualizar_relatorios', 'Pode visualizar relatórios'), ('visualizar_dashboard_geral', 'Pode visualizar dashboard geral'), ('visualizar_dashboard_cte', 'Pode visualizar painel de CT-e'), ('visualizar_dashboard_mdfe', 'Pode visualizar painel de MDF-e'), ('visualizar_dashboard_financeiro', 'Pode visualizar painel financeiro'), ('visualizar_dashboard_frota', 'Pode visualizar painel de frota')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAcessoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_afetado_nome', models.CharField(max_length=150)),
                ('acao', models.CharField(max_length=40)),
                ('antes', models.JSONField(blank=True, default=dict)),
                ('depois', models.JSONField(blank=True, default=dict)),
                ('motivo', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('origem', models.CharField(default='painel', max_length=20)),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_acesso_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_afetado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_acessos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de acesso do usuário',
                'verbose_name_plural': 'Auditorias de acesso dos usuários',
                'db_table': 'auditoria_acesso_usuario',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['usuario_afetado', 'criado_em'], name='auditoria_a_usuario_a0ea8f_idx'), models.Index(fields=['ator', 'criado_em'], name='auditoria_a_ator_id_446c76_idx')],
            },
        ),
        migrations.RunPython(preparar_permissoes_especiais, migrations.RunPython.noop),
        migrations.RunPython(
            criar_configuracoes_existentes,
            remover_configuracoes_existentes,
        ),
    ]
